### ISSUE TITLE
Préciser Charte et univers graphique souhaité

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/Vie-de-l-asso#13]
Déjà des éléments (questionnaire Clémentine) rempli par Rachel, Hugo, Mathieu. 
Des précisions sur l'univers graphique que l'on souhaite pour les CdlT à apporter. 

Merci de vos apports...

**Comment by GuillaumeAV** [comment]
Yop ! 
Sur le [doc partagé avec Edward](https://docs.google.com/document/d/1gl0Bf8gjAmyuNvRMz_W9dvwBOgx27hoXeH8wmnnrEdI/edit?usp=sharing), j'avais renseigné ces éléments :

Il s’agit plus ou moins d’une université nomade et décentralisée autour des enjeux et des métiers de la Transition. Basée sur les dimensions suivantes :

- Education, connaissance, transmission, communauté apprenante, partage de compétences, d’expériences, de savoirs-faire, université, multiversité .. 
- Compagnonage, woofing, apprendre en faisant, apprendre en voyageant
- Réseau, archipels, écosystèmes d’acteurs et d’initiatives décentralisés, autonomes et relliés, pair à pair, prenant la forme de graphes 
- Open data, partage des données, bons plans, bonnes pratiques, réseau d’entraide, communauté apprenante (ca revient) 
- Territoires : Perçus comme une infrastructure distribuée des savoirs-faire et de la connaissance …
