### ISSUE TITLE
Inviter membres manquants sur Github

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/Vie-de-l-asso#22]
Inviter membres manquants (noyau) sur Github
Ex: Rachel

**Comment by GuillaumeAV** [comment]
Yop ! Je viens d'inviter Rachel ;-)
Pour invite quelqu'un c'est très simple, tu peux les ajouter à partir de l'[onglet people à la racine du github cdlt](https://github.com/orgs/chemins-de-la-transition/people) ;-)

**Comment by J9rem** [comment]
Petite question : si c'est récurrent, ne serait-ce pas un des engagements d'un rôle à définir ?
Pour ne garder sur GitHub que ce qui concerne les actions non récurrentes. ;-)

**Comment by GuillaumeAV** [comment]
En effet - rôle onboarding je dirais ;)
