### ISSUE TITLE
Organiser la plénière du 18 mai 14h30

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/Vie-de-l-asso#24]
### Proposition d'ordre du jour :

- Revue des dernières avancées (45mn)
    - Grand est 
    - Normandie 
    - Occitanie 
    - Plateforme 
    - Gestion asso
        - Outils de travail (démo)
        - Finances
        - Communication
- Rétrospective  (45mn)
    - Quels sont nos feedbacks, comment pourrait-on s'améliorer ? 
- Planning pour la suite (45mn)
     - Qu'est-ce qu'on fait
     - Qui fait quoi ?

_N'hésitez pas à faire des suggestions dans le fil de commentaires !_

**Comment by Mathieu-CdlT** [comment]
Lien pour la plénière : 
Sujet : Plénière CdlT du 19 mai 2020
Heure : 19 mai 2020 02:00 PM Paris

Participer à la réunion Zoom
https://us02web.zoom.us/j/3158884715

ID de réunion : 315 888 4715
Une seule touche sur l’appareil mobile
+33170372246,,3158884715# France
+33170379729,,3158884715# France

Et le doc de suivi de réunions : 
https://docs.google.com/document/d/1hrxon0RudLV0qcBEPePYRlxRBasd7RvRai9y2bUQZac/edit#
