### ISSUE TITLE
Organiser l'AG du 17 juin

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/Vie-de-l-asso#25]
### Proposition d'ordre du jour

**Matin : Atelier sur le plan stratégique et le modèle économique**

- Présentation des projets correspondants 
- Mise en discussion en vue de les améliorer 

**Midi : déjeuner pour celleux en présentiel**

**Après-midi : AG statutaire**
- Rapport d'activité
- Rapport financier
- Rapport moral 
- Présentation et vote du plan stratégique 
- Présentation et vote du projet de cotisations

**18h : Apéro et célébration de ce temps fort des Chemins de la Transition !**

**Comment by GuillaumeAV** [comment]
Focuser sur : 

- Présentation pré-AG
- Préparer résolutions 
- Relancer le CA 
- Lire l’édito
- Finaliser le BM canvas..pour présentation et éventuelle sollicitation des participants à l’AG pour finalisation

**Comment by J9rem** [comment]
Bizarre, cette issue n'est pas fermée même si elle est dans 'fait !'. Est-ce normal ?

**Comment by GuillaumeAV** [comment]
Ca y est elle est fermée :)
