### ISSUE TITLE
Organisation Architecture Github

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/Vie-de-l-asso#26]
#Casquetterelou : Multiplication des dossiers à la racine du Github: 

- Tuto
- Code Social
- Ecoystème transmédiatique
- Plateforme
- Documentation
- Parcours
- Gestion Asso. 

C'est quoi le prochain ? Si on part comme ça on en a 30 dans 6 mois et on n'y voit plus rien. Contreproductif. Gros point d'attention. J'aurais dit. C'est pas la première fois. Se pencher sur une architecture d'organisation est essentiel (à documenter dans tuto par exemple). Comment solutionner le pb de Github de pas pouvoir faire une architecture et des sous branches? Merci de votre attention. 

Pour moi code social ca va dans un dossier genre admin ou com. Idem pour Ecosysteme transmédia, dans Com. 
Plateforme doit pouvoir intégrer le SemApps, mais aussi GogoCarto ou WordPress. Titre trop réducteur? 
Documentation, dans com? 

Merci aux porteurs du chantier Github de vos éléments de réponse / actions. Sinon j'en connais un qui va décrocher très vite. 

Voilà voilà. #Jaifini

**Comment by GuillaumeAV** [comment]
Hey je ne crois pas qu'il y en aura 30 dans 6 mois ... 

Cela dit tu as raison, si ce n'était que moi j'aurais rassemblé ecosystème transmediatique / doc et comm dans un seul truc .. 
Les tutos on pourrait les basculer soit dans l'onglet wiki soit dans un readme.. Voici mes premières propositions, qu'en penses tu de ton côté @Madame-K ?

**Comment by Madame-K** [comment]
Mathieu pointe du doigt ce que je redoutais depuis le début. Mais avec ma (toute petite) connaissance de l'outil, je dirais que c'est aussi l'intéret de github: chaque dépot correspond à un "projet". Quand un projet est stabilisé, on peut l'intégrer dans un projet plus "haut". bon, le hic, c'est que je ne sais pas encore faire ça techniquement (d'après la théorie, il faut commiter avec des lignes de codes git, et je n'y comprends pas grand chose pour le moment... dsl).
C'est aussi pour ça que j'ai proposé la carte mentale des différents groupes de travail : on pourrait avoir un dépot par groupe de travail, qui permet une meilleure visibilité (normalement, chaque groupe sait ce qu'il a à faire).

 Et oui, l'idée d'un wiki, plus "user friendly" est pertinente.

Pour ma part, communication et univers transmédiatique c'est la meme chose.

Dans documentation je verrais bien les tuto (pour utiliser github, wordpress, matrix....)

Le code social est délicat à traitrer : à mon sens, ce n'est pas du tout de la com', c'est ce qui explicite le fonctionnement de l'asso (il tient d'ailleurs lieu de réglèment intérieur dans les statuts : mais il manque à mon avis pas mal de chose sur la gouvernance...), ainsi que de feuille de route avec lequel on se projette (et là, à part la création d'une scoop, il ne dit pas grand chose...)

**Comment by GuillaumeAV** [comment]
Yop ! 

Je ne sais plus ou elle est ta carte mentale @Madame-K, tu peux la reposter ici ? 

Perso très motivé pour fusionner Doc / comm' / écosystème transmediatique (Franck voulait avoir son petit repo perso mais je crois qu'on peut le convaincre :-) )
Sachant qu'à l'intérieur on peut faire autant de sous dossiers qu'on veut ... tout en ayant le même ou plusieurs kanban. Pour les tutos, je les mettrais bien dans le wiki du repo doc & comm .. 
Le repo code social pourrait disparaitre, on pourrait créer uniquement un kanban dédié, si on considère que le kanban peut-être un bon outil d'intelligence collective .. 

On aurait donc quatre grands repositories : 
* Plateforme 
* Parcours 
* Gestion Asso 
* Doc & Comm' 

Qu'en pensez vous ? La bise !

**Comment by GuillaumeAV** [comment]
A la réflexion, j'irai un peu plus loin pour la gestion de projets (le kanban / trello) : 

* Je fusionnerais : Gestion asso et Doc & comm' avec par exemple un intitulé du style Vie de l'asso. 
* Je renommerais : Parcours en "Référencement lieux et création de parcours"
* Je garderais plateforme 

Qu'en pensez vous @Mathieu-CdlT @bouviermullerp @Madame-K ?

**Comment by GuillaumeAV** [comment]
Qui s'occupe de cette to-do ? Il faudrait qu'on identifie un rôle Responsable SI non ? @bouviermullerp ?

**Comment by bouviermullerp** [comment]
C'est plus de la DOC (organisation) que SI (technique) - il me semble que tu as formulé une proposition avec laquelle je ne lis pas d'objection, elle peut servir de spécification à quelqu'un qui s'occupe de réorganiser le github en respectant la dite spécification - non ?

**Comment by GuillaumeAV** [comment]
En effet :)
Je pourrais éventuellement m'en occuper mais je crois que c'est un sujet qui pourrait t'intéresser aussi non cher @bouviermullerp ?

**Comment by bouviermullerp** [comment]
@Mathieu-CdlT @J9rem @MargauxSchulz qu'en dites vous ?Est-ce ok avec vous de simplifier les projets et de regrouper les informations ?

**Comment by J9rem** [comment]
pour moi, totalement OK pour la sobriété d'information.
En plus, ça te touche pas trop `Plateforme`, donc aucun souci

**Comment by bouviermullerp** [comment]
Done
