### ISSUE TITLE
Recrutement service civique

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/Vie-de-l-asso#34]
Source : https://www.service-civique.gouv.fr/missions/permettre-a-tou-te-s-de-se-former-aux-enjeux-et-aux-metiers-de-la-transition 

**Questions**

- Décision 
- Encadrement
- Territoire
- Missions

**Candidatures**
https://docs.google.com/document/d/1VCY2ve3z2E8EhtdzokOUtysUJmpj1Ol_PJVSHmrPGOI/edit?usp=sharing

**Comment by GuillaumeAV** [comment]
@bouviermullerp @Mathieu-CdlT @laurecoplo 

J'ai ajouté Pierre qui est chaud pour suivre la discussion  : 
Pour rappel la réunion sur le sujet c'est le mardi 7 à 10h. 
Est-ce qu'on calerait pas des créneaux de rdv dès à présent ? 
Proposition : Jeudi 9 matin de 9h30 à 12h30 en fonction du nombre de candidats ... Des indisponibilités de votre côté ?

**Comment by GuillaumeAV** [comment]
@bouviermullerp @Mathieu-CdlT @laurecoplo désolé d'avoir du quitter précipitemment ! 

D'après ce que j'ai compris de votre conclusion, il y a un enjeu de rédaction d'une fiche de poste et d'un calendrier :) Vous me dites si je peux aider ? 
J'ai renseigné [les candidats avec ordre de passage sur le doc candidature au chapitre CdlT](https://docs.google.com/document/d/1VCY2ve3z2E8EhtdzokOUtysUJmpj1Ol_PJVSHmrPGOI/edit#heading=h.xd7eiry5mtjf)

**Comment by bouviermullerp** [comment]
Jeudi 9 matin, Laure, Guillaume, Mathieu et moi-même avons fait passé 3 entretiens.
Nous avons sélectionné une candidate qui sera sous la responsabilité de Laure au moins cet été.
Nous avons offert un service civique à l'Assemblée Virtuelle pour une 2eme profil.
