### ISSUE TITLE
Accueil abonnés FB

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/Vie-de-l-asso#38]
Rédiger un message pour la fonctionnalité accueil

**Comment by GuillaumeAV** [comment]
Proposition de message : 

Salut à vous, chers nouveaux venus sur les Chemins de la Transition, on est très heureux de vous accueillir ici ! 

Quelques petites infos : 
Le projet est en amorçage, ce qui veut dire qu'il n'est pas encore opérationnel (on vise l'automne) et qu'on a besoin de bonnes âmes pour le faire avancer. => Si vous avez du temps et que vous êtes motivés, vous pouvez nous rejoindre sur notre chat : https://riot.im/app/#/room/#chemins-transition:matrix.virtual-assembly.org
Il se peut que vous galériez un peu mais le jeu en vaut la chandelle. Une fois arrivé sur le chat, vous découvrirez la superbe équipe autour du projet. Si vous avez du mal à vous inscrire, écrivez un mail à bonjour@lescheminsdelatransition.org, on volera à votre secours ;) 

Par ailleurs, tous les lundis à 17h, on fait notre petite réunion hebdo (partage actus, planification chantiers) en visio. C'est l'endroit idéal pour découvrir le projet et embarquer dans l'aventure ! Le lien de la visio est communiqué sur le chat quelques minutes avant à chaque fois !  

Dans tous les cas, on vous partagera des nouvelles fraiches sur ce groupe régulièrement.

Ravis de vous compter parmi nous, à très bientôt ! 
L'équipe des Chemins de la Transition

**Comment by GuillaumeAV** [comment]
Doc mutualisé créé par Jérémy : https://docs.google.com/spreadsheets/d/1PI8JOW8HACDxS0IIinxVMedhuwi1y80uDreKnOVfNOI/edit?usp=sharing

**Comment by J9rem** [comment]
Par rapport au document de @JereM69, il serait souhaitable d'ajouter dans le message type une formulation comme : 

Afin de pouvoir vous répondre et assurer le suivi de votre demande, nous conserverons vos coordonnées personnelles (prénom,nom, adresse e-mail, téléphone, nom du profil Facebook et thématique de votre question) au sein de nos documents de travail.
Pour en demander la modification ou la suppression, veuillez contacter adresse@email.contact
