### ISSUE TITLE
Suivi des contacts

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/Vie-de-l-asso#44]
Avancer sur la gestion du fichier de contact pour le rendre plus compatible RGPD.

**Comment by J9rem** [comment]
un document de mutualisation de contact a été créé https://docs.google.com/spreadsheets/d/1PI8JOW8HACDxS0IIinxVMedhuwi1y80uDreKnOVfNOI/edit#gid=0.
Comment est-on compatible avec la [RGPD ](https://www.economie.gouv.fr/entreprises/reglement-general-sur-protection-des-donnees-rgpd)?

**Comment by GuillaumeAV** [comment]
Héhé bonne question, il faudrait peut-être le retirer de github ?

**Comment by J9rem** [comment]
Et si je renomme tout en suivi des contacts ? sans plus de détails

**Comment by J9rem** [comment]
Je ferme cette Issue car elle est reprise par #38
