### ISSUE TITLE
Fiche de présentation des nouveaux contributeurs

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/Vie-de-l-asso#46]
Draft de fiche de présentation réalisé : 
https://docs.google.com/document/d/1637b3g9fZ9DWLPrSxnPAlLMFgLOhJkpF/edit

L'idée serait que chaque nouveau contributeur / contributrice puisse compléter une petite fiche de présentation, afin que tout le monde puisse connaitre tout le monde (profil, motivations, compétences...) - 1 page maximum

Mettre Valentine sur le coup ? 
Est-ce qu'on veut d'autres infos ?

**Comment by J9rem** [comment]
J'ai ajouté @ValentineMathieu car elle a beaucoup avancé sur les fiches nouveaux contributeurs

**Comment by ValentineMathieu** [comment]
Voici le lien vers la nouvelle fiche de présentation ! https://drive.google.com/drive/folders/1CfngtjDxpc4Hi0DMz8Km6AmOZJf7TvqI
