### ISSUE TITLE
Brainstormer une restructuration des réunions ... 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/Vie-de-l-asso#55]
Proposition initiale  : 

- Réunion plateforme
- Réunion parcours
- Réunion gestion asso
- Réunion accueil des nouveaux et news où les référents des réunions spécialisées (au moins), partagent les news...

**Comment by J9rem** [comment]
Je fais un premier test pour une réunion Plateforme.
On va voir, ....

**Comment by GuillaumeAV** [comment]
Pour la réunion gestion asso, on se dirige vers le mercredi à 10h .. https://framadate.org/pPwh5w9yW1Fk92OH
