### ISSUE TITLE
un rôle "documentation" ?

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/Vie-de-l-asso#59]
Les informations, documents des chemins de la transition sont réparties à plusieurs endroits :
- Google Drive
- Github
- Gare Centrale
- Site internet
- Pad les communs/hack.md

Pour tendre vers une simplification, harmonisation de tous ces supports, les référents concernés devront faire des choix (suppression de données, rangement, etc)
Est-ce que ça ne serait pas plus facile de définir un rôle "documentation" (nom temporaire) pour transférer aux référents de ce rôle la responsabilité de pouvoir choisir sans solliciter toute la communauté à chaque fois ?

_tag `ODJ` : ordre du jour pour signifier que cette issue est un sujet pouvant être ajouté aux prochaines réunions "Gestion Asso"_

**Comment by Mathieu-CdlT** [comment]
Hello, 

Pour ma part et pour un accès commun à l'information et aux documents qui sont produits, avoir une lecture des avancées (et historique) des productions et discussions, je suggère que les documents soient stockés sur le Drive (pas de stockage possible sur Github...). Jusqu'à présent c'est là que l'on stocke les données et la "mémoire" des CdlT. 

Pour ce qui est des réunions, de l'ODJ, il pourrait y avoir un doc de suivi de réunions à l'instar de ce qui se fait actuellement sur les réunions du Lundi où de façon centralisée on puisse avoir tout l'historique. L'ODJ pourrait être renseigné sur ce doc (incrémentable par tous les participants). J'ai peur que mettre l'ODJ sur le Github surcharge inutilement le Github (déjà plus de 50 issues sur "Plateforme" dont les 2/3 datent du mois d'Avril et n'ont pas encore été soldées).

**Comment by J9rem** [comment]
Salut @Mathieu-CdlT ,
merci pour la précision sur le lieu de stockage des informations, habituel jusqu'à la création de la gare centrale et l'utilisation de GitHub...
Ceci viendra porter des arguments à la discussion.

Pour l'ODJ, bonne proposition.
Quel dossier verrais-tu ? Quel nom de fichier ?
Chemins de la Transition/Réunions d'équipe & Résidences/Gestion Asso/ODJ.docx ?

Mon expérience de ce genre de document est qu'il est préférable d'attribuer une note d'urgence et d'importance à chaque thématique pour mieux les sélectionner et aussi de retirer es sujets déjà aborder pour le rendre plus clair.
L'historique risque de surcharger d'information.

**Comment by GuillaumeAV** [comment]
Ouvert à tout de mon côté :)

**Comment by J9rem** [comment]
Sujet ajouté à l'ordre du jour du 17 août : https://docs.google.com/document/d/1hrxon0RudLV0qcBEPePYRlxRBasd7RvRai9y2bUQZac/edit#heading=h.r8jnzc57cz15
car c'est un endroit plus accessible à tous

contrairement au GitHub qui est plus facile à prendre en main par les développeurs et suiveurs de projet.

=> fermeture de ce sujet + retrait du tag ODJ
