### ISSUE TITLE
Rédiger la charte CdlT

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/Vie-de-l-asso#6]
Périmètre : 
* Droits et devoirs des lieux 
* Droits et devoirs des voyageurs 

To-do
* Benchmarker les bonnes chartes 
* Identifier les bonnes pratiques 
* Concevoir une v0 en lien avec le Code Social 
     * Créer pour cela un groupe de travail avec différentes parties prenantes ... lieux, voyageurs, partenaires ... 
          * Lieux : William Dufourcq - Franck Zimmerman - Hélène / Igor & co - Lilian 
          * Voyageurs : Christian - Hugo - Aurélie - Yannick ? 
          * Partenaires : Francois Deroo - Ameline - Nicolas Voisin ... 
* La soumettre au collectif. 

Temporalités : 
* Version beta simple et efficace pour l'AG
* Version 1 pour la rentrée septembre ... 

Référent : Hugo

**Comment by Madame-K** [comment]
Exemple du protocole de participation, du mouvement d'éduc pop culture et liberté http://paulmasson.atimbli.net/site/IMG/pdf_FOP_le_protocole_de_cooperation.pdf

**Comment by Mathieu-CdlT** [comment]
Travail perdu sur la Charte mais néanmoins j'avais collectionné un certain nombre de documents que vous trouverez sur le [Drive](https://drive.google.com/drive/folders/14Gjrk6SoH0IilSfCz-a6Y8oJ_u18MaBM). C'est assez varié et inégal mais je pense qu'en terme de procédé on pourrait : 

1. recenser un certain nombre de chartes (stockées dans le dossier exemples)
2. Lire attentivement et piocher ce qui peut nous interesser qui puisse être adapté aux CdlT
3. Travailler à partir de cette matière récoltée au développement  de la charte des CdlT. 

J'imaginais qqch comme: 
1. Les objectifs et valeurs des CdlT
2. Les engagements globaux
3. Les engagements spécifiques aux initiatives accueillantes 
4. Les engagements spécifiques aux voyageurs apprenants.

Je pense qu'il faut qu'on sorte une V1 de la Charte entre nous, qu'ensuite on la partagera et la soumettra aux amendements et commentaires des parties prenantes. Et pas la constitution d'un groupe de travail multi acteurs pour sortir la V0. Sinon dans 2 ans on y est encore et puis en tant que porteur de projet on est sensés avoir une "vision", qu'on commence par la coucher sur papier avant de la challenger.

**Comment by Mathieu-CdlT** [comment]
Bon j'ai pris le taureau par les cornes et j'ai pas mal bossé et avancé sur la Charte, vous avez une V1 dans le dossier éponyme sur le drive : https://drive.google.com/drive/folders/14Gjrk6SoH0IilSfCz-a6Y8oJ_u18MaBM. 

Je l'ai également passé à une pote (pas loin de la porte d'embarquement Occitanie) qui va me faire ses retours / commentaires dessus.
