### ISSUE TITLE
Budget participatif 64 

### ISSUE THREAD

**Issue by bouviermullerp** [chemins-de-la-transition/Vie-de-l-asso#63]
Il y a 50 000 euros à récolter dans les Pyrénées Atlantique (64) -> https://www.budgetparticipatif64.fr/projects/le-budget-participatif-64/collect/etape-de-depot-des-idees/proposals/les-chemins-de-la-transition?_locale=fr-FR

Le dépot de dossier est assez succint (pour la première étape en tout cas)

J'ai écrit ce [petit texte](https://docs.google.com/document/d/1-qIuzVrZ9qv5QUTCM9Ak53zEAlH1hUeXwJc6TvLuiyA/edit#heading=h.hbf82ererfxy)

**Comment by bouviermullerp** [comment]
@Mathieu-CdlT @GuillaumeAV -> votre relecture est précieuse !

**Comment by GuillaumeAV** [comment]
Génial !! J'ai relu, corrigé quelques fautes et fait quelques commentaires ;)

**Comment by Mathieu-CdlT** [comment]
Quelques commentaires faits aussi, dsl j'avais pas vu :(

**Comment by Mathieu-CdlT** [comment]
Yo @bouviermullerp ! J'ai regardé tes docs, super! Je me suis permis de rajouter une initiative de Sauvagnon "La Halle Paysanne"  https://www.facebook.com/LaHallePaysanne64/ 
Par ailleurs dans le dossier de présentation des CdlT, je rajouterais le développement en Normandie. Tu parles de Gd Est et Occitanie  mais y'a pas la normandie (qu'il n'y avait pas qd j'ai fait ce dossier). 
Coté Budget, je me demande si il n'y a pas trop de dépenses sur les frais kilométriques et que peut être tu pourrais mettre une partie de ce budget sur de l'ingénierie pédagogique (temps de travail dans la partie coconstruction des parcours). 
Enfin et sauf erreur, mais y'a pas de temps de travail sur la partie référencement / construction de parcours, ca pourrait pas mal d'en mettre. Voilà voilà pour mes apports. 
Hésites pas à appeler la personne en charge, pour créer de l'interpersonnel. 
La bise et bon we!

**Comment by bouviermullerp** [comment]
Budget déposé, disponible dans le drive.
