### ISSUE TITLE
Structurer l'organisation des CdlT

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/Vie-de-l-asso#67]
**Objectifs:** 
- Trouver un modèle de structuration de l'organisation du projet / Asso CDLT
- Fluidifier la circulation de l'information 
- Définir les objectifs de chaque cercle de travail, les attendus.
- Définir les roles et responsabilités des différents cercles et référent.e.s
- Définir un mode de processus de décision 
- travailler sur les outils de travail / communication - clarifier ou va quoi
- Réorganiser Drive / GitHub / Element pour qu'ils soient en concordance les uns avec les autres 

**Document de travail de réflexion sur l'organisation des CdlT (Draft - à martyriser)**: 
https://docs.google.com/document/d/1bw2Ms8SPsBeiTI0qhlFbx4cpz7-ec3n4uag8w02Qzg0/edit

**Attendus de la réflexion collective:** 
- Compléter le document de travail, faire en sorte que rien ne soit oublié et que toutes les dimensions soient abordées
- Au terme de cette réflexion collective, prise de décision et clôture de ce sujet (point de validation à réaliser dans 3 mois). Mise en place de la nouvelle organisation. Le document "Organisation CDLT" fait foi et permet en cas de doute de s'y référer. 

**Enjeux:** 
- Travail fondamental à réaliser en urgence pour avoir une organisation qui fonctionne et en capacité d'aller de l'avant. 

**Travail à faire: **
- En mode sprint : première étape du sprint : Mercredi 02/09 à 10h pour la réunion Gestion Asso. Retour sur les commentaires / apports / enrichissements apportés par les contributeurs sur le document. 
- D'ici là, à vos réflexions et merci par avance !

**Comment by J9rem** [comment]
Super boulot @Mathieu-CdlT 
Je suis un peu embêté avec la formulation
>Définir les roles et responsabilités des différents cercles et référent.e.s

En effet, je pense que l'objectif était bien plus léger dans un premier temps.
Il n'est que de définir des besoins (des rôles) sur lesquels nous allons élire/définir des référents.
Ceci permet de ne pas entrer dans la lourdeur de la création des cercles qui sera évidemment bienvenue dans un second temps.

>Réorganiser Drive / GitHub / Element pour qu'ils soient en concordance les uns avec les autres

ne serait-ce pas la responsabilité d'un rôle à élire justement et donc ça ne serait plus dans notre objectif d'équipe

>travailler sur les outils de travail / communication - clarifier ou va quoi

Ne serait-ce pas la raison d'être d'un rôle communication justement ?

**Comment by Mathieu-CdlT** [comment]
"Définir les roles et responsabilités des différents cercles et référent.e.s" --> J'ai repris mot les mots de Guillaume dans la réunion d'hier. 

Je pense qu'on a un travail à faire de structuration. Faut qu'on avance et qu'on débloque cette situation grippée et qu'on aille de l'avant rapidement. 

Hate pour ma part d'avoir qqch de cohérent, des perimetres et priorités de travail, roles et responsabilités clarifiés, et qu'on soit en mode on avance efficacement et avec un système d'organisation où les infos tournent.  Alors peut être que ca va un peu plus loin que ce qu'on avait discuté mais il me semble que ces aspects sont liés et qu'il est bien de les aborder également. Car si chaque outil a une architecture différente, on perd des informations, en efficacité, and so on...

**Comment by J9rem** [comment]
Je suis tout à fait d'accord sur ce que tu dis.
Je propose juste de trier les informations entre :
- l'objectif principale de cette Issue `Structurer l'organisation des CdlT`
- et le contenu de chaque rôle/cercle. par exemple, l'architecture de chaque outil est peut-être à mettre dans les engagements d'un rôle

Les discussions de plus bas niveau (comment ranger les documents, comment mettre de l'huile dans les rouages de la communication) ont peut-être davantage leur place sur la définition de chaque rôle.
La discussion de plus haut niveau (quelle structure, quels rôles) est pour moi sur un autre plan.
Mélanger les deux niveaux de discussions risque de nous embrouiller.

**Comment by GuillaumeAV** [comment]
Yop ! De mon côté, je trouve le doc très complet et fidèle à nos besoins et à la réalité .. 

Je me dis que si on enlève les cercles "comm'" et "grand cercle" on retombe sur nos 3 types de réunions qui correspondent peu ou prou à des cercles ... 
=> Le cercle comm' pourrait faire partie du cercle gestion asso et s'autonomiser à terme si besoin ... 
=> Le grand cercle pourrait correspondre aux réunions mensuelles : "les plénières", et aux AG ...  

Si on est d'accord avec cette base, on pourrait se concentrer sur [les rôles (raison d'être et redevabilités) évoqués lors de la réunion ?](https://docs.google.com/document/d/1zaK96H_WmfPdxUX_ZYzRh5ZUIPwnaY822Gw36UgAhh8/edit?usp=sharing) 

Connaissant par ailleurs, les intentions secrètes de @J9rem sur la question des outils, je me dis qu'on pourrait reporter cette question à plus tard ? En tout cas, la description que tu en fais Mathieu correspond précisément à l'état actuel de notre SI, ce qui peut constituer une bonne doc pour les nouveaux contributeurs ! 

@laurecoplo & @MargauxSchulz devraient être très intéressées par cette discussion ;)

**Comment by J9rem** [comment]
J'ai dû mal à prendre part à ce document (pourtant bien construit)
Je n'y retrouve pas explicitement les rôles dont nous avons besoin (hormis les rôles référents de chaque cercle)
Alors si ce document ne parle que de la structure et non des rôles, je ne suis pas pertinent pour le commenter (car la structure est plutôt historique ou une photographie de l'état actuel sur lequel je n'ai rien à dire).
Si nous y intégrons les rôles, effectivement, je pourrais alors faire remonter les besoins qui vont amener à l'émergence de rôles.

Dans l'état actuel du document, il y a un mélange entre la structure et une ébauche des rôles et responsabilités.
par souci de clarté, soit on sépare tout, soit on met tout dans le même document, mais dans l'état c'est difficile à suivre.

**Comment by J9rem** [comment]
Suite à la réunion Sprint du 16 septembre 16h30 :
- @laurecoplo reformule les objectifs du cercle Parcours et des thématiques associées (avant le mercredi 23 septembre)
- @GuillaumeAV a travaillé la fusion du [document de travail actuel](https://docs.google.com/document/d/1bw2Ms8SPsBeiTI0qhlFbx4cpz7-ec3n4uag8w02Qzg0/edit#) avec les travaux de l'issue #74 [Besoins, rôles et référents pour les points bloquants au 4 septembre 2020](https://docs.google.com/document/d/1kcEh_WVrLKxItvYU6obM67vMOLiDNYB606p0GkmiGXg/edit#heading=h.sinnc8v5bl83) pour donner le [document de fusion](https://docs.google.com/document/d/1u6-La_Mk4jLrcF8dqfKgF3u-5-rZA6DsYUgnqbvKO04/edit#) ([schéma associé](https://guillaumeav.kumu.io/schema-gouvernance-cdlt))
- le [document de fusion](https://docs.google.com/document/d/1u6-La_Mk4jLrcF8dqfKgF3u-5-rZA6DsYUgnqbvKO04/edit#) n'est pas le document de travail. @GuillaumeAV s'occupera de faire la fusion après la finalisation du [document de travail actuel](https://docs.google.com/document/d/1bw2Ms8SPsBeiTI0qhlFbx4cpz7-ec3n4uag8w02Qzg0/edit#)
- Tout le monde peut prendre connaissance du [document de fusion](https://docs.google.com/document/d/1u6-La_Mk4jLrcF8dqfKgF3u-5-rZA6DsYUgnqbvKO04/edit#) pour faire remonter les commentaires ici
- @J9rem a fait des propositions de modifications de la partie définition des cercles, qu'il faudra valider, modifier ou refuser
- Penser à intégrer aussi les remarques sur la prise de décisions évoquée lors de la [réunion Vie Asso du 16/09](https://docs.google.com/document/d/1zaK96H_WmfPdxUX_ZYzRh5ZUIPwnaY822Gw36UgAhh8/edit#)
- **To-dos** :
    - On lit le doc de Guillaume d'ici à vendredi. 
    - Vendredi à 15h on se fait un call de 15mn pour discuter du doc de Guillaume. 
    -  Description des rôles : Pas d'urgence, @laurecoplo pourra décrire les rôles parcours, @JereM69 les rôles comm, @J9rem les rôles plateforme, @Mathieu-CdlT & @GuillaumeAV les rôles vie asso .

**Comment by J9rem** [comment]
ET surtout nous pensons bien à utiliser le canal Vie-Asso pour les communication plutôt que des canaux privés.

**Comment by J9rem** [comment]
Pour la description des rôles pour la plateforme, ça risque prendre beaucoup de temps car nous n'avons pas le même rythme de réunions que les autres cercles et ça n'est pas un sujet nécessaire dans un premier temps pour la plateforme.
Je pense plutôt pouvoir proposer les rôles de la plateforme fin octobre

**Comment by pruls** [comment]
1) 
Est il possible de désigner un **rédacteur en chef** qui se charge de nettoyer le doc de travail au fur et à mesure, il m'est difficile à lire en l'état?

2) 
Il me semble qu'il y a 2 approches qui s'entrechoquent car elles ne sont pas explicites. D'un côté, une volonté de poser une structure, de l'autre une volonté de révéler celle qui est déjà là.

C'est le **contrôle/prévision vs l'émergence/surprise**.

L'émergence est compatible avec la notion de structure, il s'agit de définir comment se comporter quand un truc émerge. Autrement dit quand un projet émerge.
L'organisation du projet revenant à ceux qui bougent dedans, avec les limites posées par les fonctionnements des autres.

En particulier, le cercle/projet/bidule qui s'occupe de capter de l'argent.
Du moins actuellement puisqu'il semble que ça soit le modèle économique du moment. Les CDLT en sont au stade de concept, aucun parcours n'est opérationnel.
Demain, cela tombera peut être en désuétude car les flux et opportunités auront changé, et un autre machin/modèle éco émergera.

3) 
Sinon, pour chipoter sur les mots et les concepts: peut être que la notion de **livrable** serait plus facile  que **raison d'être** qui peut paraitre encore abstraite? 
Voir ici où Frédéric Lalou parle de raison d'être évolutive: https://thejourney.reinventingorganizations.com/videacuteos.html#6

4) 
Autre élément de réflexion. Il me semble qu'en général les groupes évoluent en méconnaissant une règle sous-jacente: la **solicitation d'avis limitée**. C'est un concept à moi, accrochez vous:
La sollicitation d'avis limitée pourrait être du style: une décision est prise par un porteur après qu'il ait sollicité l'avis d'au moins 5 personnes du collectif. Le collectif acceptant qu'une décision contraire à ses avis puisse être prise par le porteur (A qui on saura dire qu'il a abusé si ça foire).
Ainsi  jusqu'à 5 personnes, tout le monde prend part à toutes les décisions.
Mais à partir de 6, une personne peut être hors du processus. Il ne s'agit pas d'une exclusion ou d'une manoeuvre, mais de l'application pragmatique de la règle implicite.
Et donc à 30, 25 personnes peuvent être en dehors du process et que des décisions soient prises.


J'espère avoir été clair dans l'explication?
La limite peut être définie autrement que "au moins 5".

**Comment by GuillaumeAV** [comment]
Aah j'aime bien le concept de sollicitation d'avis limitée @pruls :)

**Comment by GuillaumeAV** [comment]
Par ailleurs (désolé pour le côté décousu de la réponse, on se fait un mini point vendredi à 15h sur le sujet @pruls, tu pourrais participer ?

**Comment by pruls** [comment]
Hé non, je serai en AG dans le boulot qui me paye.

Le mieux que je puisse offrir c'est des relectures.

Ça revient à proposer une sorte de regard extérieur comme le suggérait Mathieu.

**Comment by J9rem** [comment]
Concernant la solicitation d'avis limitée :
- c'est très utile pour éviter les blocages d'attente de décision
- par contre, c'est difficile de suivre les changements rapide quand on est en vacances, .... alors que la gestion par consentement permet de pouvoir porter objection avant validation de la décision (tout en permettant des décisions rapides)
-  le processus actuel pour devenir contributeur actif est juste par la présence aux réunions et l'implication. Avec un processus de sollicitation d'avis limité, il est tout à fait possible d'avoir une prise de décision par des nouvelles personnes qui éloignent des intentions d'origine.
Pour y remédier, je vois comme une des solutions, la possibilité de clarifier le processus d'accès au statut de contributeur actif, les seuls à pouvoir participer à la sollicitation d'avis limitée.

En conclusion :
- selon moi, sollicitation d'avis limitée = définition plus stricte pour accéder au statut de contributeur actif
Est-ce compatible avec nos intentions d'ouverture du groupe ?

**Comment by J9rem** [comment]
Philosophie:
La structuration est en puissance quand elle reste en support de l'émergence. Il y a ressenti de détachement entre la structuration et l'émergence quand on part sur le contrôle/prévision.
 - Émergence = accueillir les initiatives du terrain
 - Contrôle/prévision =  anticiper l'avenir pour répondre parfois à des peur (parfois cachées) = la projection

Typiquement, la recherche de financement amène des projections qui perturbent l'émergence (initiative du terrain).
Il peut exister alors des tensions (internes ou inter-personnels)

Je tournerai certains de mes commentaires dans les documents dans ce sens.

**Comment by pruls** [comment]
Une autre clé est de préciser la typologie des personnes à solliciter.

Exemple: solliciter au moins 5 personnes, dont les experts/personnes ressources pertinents, avant de pouvoir prendre une décision.

Si l'expert est en vacances, on doit attendre.

A noter qu'un avis peut être "aller poser une question à une personne ressource" , donc cela affaibli l'intérêt de le préciser dans la régle.

Clarifier des paliers pour obtenir de nouveaux droits/devoirs me paraît très aidant en ce que cela amène de la visibilité.
Un défi est de garder ça bête et con, en préférant accueillir les peurs plutôt qu'alourdir de manière excessive, chaque fois que c'est possible.


Je pianote en réunion, j'espère que vous vous amusez mieux que moi!

**Comment by J9rem** [comment]
Au fait @pruls , nous avons convenu ce vendredi que :
- Laure est la garante de la simplicité et synthèse du [document actuel de travail]. Elle va trier et nettoyer les commentaires et propositions, elle va inclure les contenus du [document de fusion] dans le [document actuel de travail]
- Je me suis proposé pour l'aider en relecture même si je ne pourrai pas participer aux prochaines réunions;

[document actuel de travail]: https://docs.google.com/document/d/1bw2Ms8SPsBeiTI0qhlFbx4cpz7-ec3n4uag8w02Qzg0/edit#
[document de fusion]: https://docs.google.com/document/d/1u6-La_Mk4jLrcF8dqfKgF3u-5-rZA6DsYUgnqbvKO04/edit#

**Comment by J9rem** [comment]
A relire jusqu'au 8 octobre pour les objections éventuelles

**Comment by J9rem** [comment]
J'ouvre à nouveau cette Issue car:
- il existe un document de suivi des activités : https://docs.google.com/document/d/1k7p-lGhbMlq6EumQCKwIfGU3gm1W-0QR/edit
- à mettre à jour et à inclure dans notre document de strucuturation.
Je m'en charge cette semaine.

**Comment by J9rem** [comment]
@laurecoplo j'ai ajouté dans le documentation structuration le lien dans chaque cercle vers le [Fichier de suivi des activités CDLT 2019-2020](https://docs.google.com/document/d/1k7p-lGhbMlq6EumQCKwIfGU3gm1W-0QR/edit)
J'ai aussi rajouté une redevabilité du référent de chaque cercle de tenir ce document à jour.
Est-ce que tu pourrais relire rapidement le document pour vérifier que c'est correct en validant mes propositions de modifications ?
Merci

**Comment by J9rem** [comment]
A priori, le temps des objections est passé.
Considéré comme tâche terminée
