### ISSUE TITLE
partager la liste déjà établie des contributeurs avec Mathieu

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/Vie-de-l-asso#69]
cf. [CR du 26 août](https://docs.google.com/document/d/1zaK96H_WmfPdxUX_ZYzRh5ZUIPwnaY822Gw36UgAhh8/edit)

**Comment by MargauxSchulz** [comment]
lien ici : https://docs.google.com/spreadsheets/d/1jjBh89yew02CXXTOU_kqvgBIfFZc43Hix2XEUDX9RVI/edit#gid=0

**Comment by J9rem** [comment]
Est-ce que tu as toutes les informations @Mathieu-CdlT ? (- fermer la fiche si c'est bon out toi)
