### ISSUE TITLE
organiser une réunion pour parler de la gestion communautaire selon JM Cornu

### ISSUE THREAD

**Issue by MargauxSchulz** [chemins-de-la-transition/Vie-de-l-asso#70]
David propose de prendre une heure afin de nous éclairer et d'ouvrir l'échange sur la notion de gestion communautaire telle que présentée par JM Cornu. 

Vous trouverez ci-dessous le framadate à remplir afin de convenir d'un horaire :
https://framadate.org/xFth2XNQgFFqsd35

Ainsi que le lien vers ses notes : 
https://drive.biensurterre.fr/s/3ZL2YMZXM52PiZb

Et le lien vers le CR : https://docs.google.com/document/d/14Dh1QFU3ML4Op_hbi5fBOCvCG27RAl5GJcGngAdf1Zg/edit

**Comment by pruls** [comment]
Est-il possible d'élargir le sondage de date à la semaine prochaine?

**Comment by MargauxSchulz** [comment]
yes, et voilà !

**Comment by J9rem** [comment]
@MargauxSchulz a priori si je ne me trompe, la réunion est organisée (bravo).
Si c'est le cas, tu peux clore directement cette fiche.
