### ISSUE TITLE
Créer une check-list permettant à chaque contributeur actif de veiller à la bonne adhésion des nouveaux contributeurs

### ISSUE THREAD

**Issue by ValentineMathieu** [chemins-de-la-transition/Vie-de-l-asso#71]
Superbe idée émise par @J9rem qui permettrait à chacun d'entre nous, membres actifs des CDLT, d'avoir un support permettant de vérifier qu'un nouveau contributeur a accès à tout ce dont il a besoin pour collaborer aux projets des CDLT. 
Je vais créer une pull request que chacun pourra compléter en fonction de ce qui lui semple pertinent à ajouter !

**Comment by J9rem** [comment]
Vu que tu as une pull request associée, je me demande si c'est pertinent de conserver cette issue qui reprend les mêmes informations ?
En tout cas, beau travail. J'ai ajouté mes commentaires.

**Comment by ValentineMathieu** [comment]
Merci pour tes commentaires j'y jette un coup d'oeil de suite ! :) J'ai pensé à créer l'issue pour "annoncer" un peu cette idée, mais c'est vrai que je peux la fermer étant donné que la request a été créée au même moment. Merci beaucoup !

**Comment by J9rem** [comment]
Donc nous pouvons fermer cette issue et continuer dans la pull-request #72
