### ISSUE TITLE
Collecter les besoins et les points bloquants pour mettre en face les référents 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/Vie-de-l-asso#74]

**Comment by J9rem** [comment]
Création d'un document pour recueillir les besoins :
https://docs.google.com/document/d/1kcEh_WVrLKxItvYU6obM67vMOLiDNYB606p0GkmiGXg/edit#

**Comment by J9rem** [comment]
@GuillaumeAV le document commence à bien se remplir.
Je pense que tu peux déjà faire un tour pour m'aider à trouver les référents actuels.

**Comment by Mathieu-CdlT** [comment]
Comment identifier les roles si on n'a pas la structure ? 
Il me semble qu'il faut d'abord définir le périmetre, avant d'attribuer les roles

**Comment by J9rem** [comment]
Ah @Mathieu-CdlT philosophons comme nous avons prévu de le faire de vive voix, je vais t'expliquer ma vision.

**Comment by J9rem** [comment]
Ce document est une base de travail pour les prochaines réunions de définition des rôles par chaque cercle.
Ce document est donc temporaire.
