### ISSUE TITLE
Sructuration : Identifier des rôles consistants à partir de la collecte des besoins et du document de Mathieu

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/Vie-de-l-asso#75]
- Collecte des besoins : #74
- [Document de Mathieu](https://docs.google.com/document/d/1bw2Ms8SPsBeiTI0qhlFbx4cpz7-ec3n4uag8w02Qzg0/edit?usp=sharing)

Lundi 2 septembre 15h - Réunion du sprint

**Comment by J9rem** [comment]
En fait c'est grosso-modo l'issue #67 , avons-nous besoin de cette nouvelle Issue ?

**Comment by GuillaumeAV** [comment]
Identique à #67
