### ISSUE TITLE
Créer un canal Vie Asso 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/Vie-de-l-asso#76]
Privé 
Inscription des gens

**Comment by J9rem** [comment]
Je veux bien être administrateur avec toi (si c'est techniquement possible).

**Comment by J9rem** [comment]
Hum hum hum, @laurecoplo n'est pas dans les invitées pour ce salon.
est-ce normal ?
Enfin, en regardant le fichier [Groupes de travail](https://docs.google.com/spreadsheets/d/1Zr5-tCLil_z2mT693Eh_L3CENJnnBTJFCUdjS5h3efo/edit#gid=0) je vois que @bouviermullerp n'est pas identifié dans ce document pour la partie Gestion-Asso alors qu'il est dans le canal Vie-Asso. Est-ce un oubli ?

**Comment by J9rem** [comment]
J'ai invité Laure.
