### ISSUE TITLE
Organiser réunion concernant la réorganisation de l'onboarding sur les CDLT

### ISSUE THREAD

**Issue by ValentineMathieu** [chemins-de-la-transition/Vie-de-l-asso#78]
L'idée serait de répondre à l'inefficacité de la fiche contact CDLT qui n'est pas tenue par les personnes concernées, en intégrant par exemple au site des CDLT directement la fiche de présentation et les étapes nécessaires pour contribuer dans de bonnes circonstances (les tutoriels d'accès et d'utilisation Github, Element...)
Peut être qu'il serait intéressant de la lier directement à la réunion prévue sur l'onboarding et notamment la gestion du Facebook ? (https://framadate.org/OzXcaBEWI6M8sIai)

**Comment by Mathieu-CdlT** [comment]
Possibilité une fois la date calée, de préparer un document de réunion avec tes principaux questionnements, l'état d'avancement sur les questions onboarding, fiche de présentation des contributeurs, liste des contributeurs, communication de la fiche de présentation, fonction et cible, décisions et points qui te bloquent, étapes, et tout ce qui te parait pertinent?

**Comment by Mathieu-CdlT** [comment]
Des éléments sur le process onboarding (.ppt) dans le dossier https://drive.google.com/drive/folders/1CfngtjDxpc4Hi0DMz8Km6AmOZJf7TvqI

**Comment by ValentineMathieu** [comment]
Très bonne idée, je me charge d'effectuer ce document afin de compléter celui que tu as réalisé, je pourrai vous le partager en amont afin que chacun puisse y réfléchir :)
