### ISSUE TITLE
Planifier l'AG

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/Vie-de-l-asso#8]
Semaine du 15 idéalement 

Est-ce qu'on propose des ateliers sur l'autre demi journée ?
Objectifs possibles : 
- Cohésion de groupe ? 
- Ateliers ? 
- Les 2 ?

**Comment by Madame-K** [comment]
**Petit mémo des choses à vérifier sur les statuts pour l'AG** 
- la personne ou l'organe responsable de la convocation les Assemblées Générales,
- le mode de convocation (courrier, mail, annonce sur panneau d’affichage, etc.),
- la fréquence des Assemblées Générales,
- les personnes autorisées à y assister,
- le quorum, c'est-à-dire le pourcentage de personnes dont la présence ou la représentation est requise pour que l'assemblée puisse valablement délibérer,
- le temps de latence entre une convocation et une Assemblée Générale.

**Comment by Madame-K** [comment]
Avant : Que doit contenir la convocation ? 
- le nom de l'association,
- la date de la convocation,
- la date, l'heure et le lieu de l'Assemblée Générale,
- l'ordre du jour,
- l'identification et la signature de l'auteur de la convocation.

**Comment by Madame-K** [comment]
Programme : légalement (mais à vérifier sur les statuts), lAG doit contenir le vote de :
- le bilan de l'année,
- le vote de budgets,
- le renouvellement des pouvoirs des responsables de votre association,
- la définition de nouveaux projets,

Et il fortement conseillé de faire un procès verbal à son issue

**Comment by Mathieu-CdlT** [comment]
S'assurer que l'on AIT LE TEMPS TERMINER DANS DE BONNES CONDITIONS le rapport annuel et les comptes de l'exercice 2019, **y compris la mise en forme**. La réalisation d'un rétro planning avec attribution de taches et de dates limites pourrait être souhaitable. 

La date de convocation doit avoir lieu 1 mois avant l'AG. 

Extrait des statuts: 
"ARTICLE 11: L’ASSEMBLEE GENERALE ORDINAIRE
1. Composition :
L’Assemblée Générale Ordinaire comprend l’ensemble des membres actifs et associés à jour de leur cotisation, répartis par collèges, à raison d’un délégué titulaire par membre si le membre est une organisation. Chaque organisation membre peut désigner d’autres délégués à titre d’auditeurs.
Les membres d’honneur participent aussi à l’Assemblée Générale en tant qu’auditeur et ont une voix consultative.
2. Convocation :
L’assemblée Générale se réunit au moins une fois par an. Elle peut être convoquée soit par le Président, soit par des membres actifs de l’association représentant au moins le quart des voix de l’Assemblée Générale.
6
Un mois au moins avant la date fixée, les membres sont convoqués par écrit ou électroniquement et l’ordre du jour, ainsi que le lieu, l’adresse et la date de l’Assemblée Générale, sont inscrits sur les convocations.
3. Délibérations :
Les procurations sont autorisées mais un membre ne peut disposer que de deux procurations d’un autre membre au maximum.
Le Président et le Secrétaire de l’association forment le bureau de l’Assemblée Générale. Le Président assure la police de l’audience et veille au respect de l’ordre du jour. Le Secrétaire rédige un procès-verbal de la séance signé par lui-même et contre signé par le Président.
En cas d’absence du Président et du Secrétaire de l’association, l’Assemblée Générale désigne un Président de séance ainsi qu’un secrétaire de séance parmi les membres présents.
Chaque membre actif ou associé, dispose d’une seule voix à l’Assemblée Générale. Un membre du bureau n’a pas le droit de vote lorsque la délibération concerne la conclusion d’un acte juridique entre lui et l’association.
Les décisions de l’Assemblée Générale sont prises à la majorité des voix présentes et représentées. Les voix sont pondérées en fonction de la répartition par collèges. Elles sont prises à main levée. Cependant un vote à bulletin secret est mis en place si un tiers des membres présents le demandent.
4. Attributions :
L’Assemblée Générale se prononce annuellement sur le rapport moral et sur les comptes de l’exercice financier. Elle pourvoit à la nomination ou au renouvellement du Conseil d’Administration. Elle fixe aussi le montant de la cotisation annuelle et, de manière générale, peut modifier le #CodeSocial.
L’Assemblée Générale délibère sur les orientations à venir et la politique de l’association. Elle peut prendre toute décision concernant l’objet de l’association.
L’Assemblée Générale est compétente pour examiner tous les points qui ne sont pas de la compétence du Conseil d’Administration et du Bureau."

**Comment by Mathieu-CdlT** [comment]
ATTENTION : Les personnes doivent être à jour de leur cotisations !!!! Attention (aujourd'hui seulement 3 personnes le sont - Guillaume, Hugo, Alice, Mathieu). Inclure la demande de mise à jour de la cotisation en gros en gras sur la convocation à l'AG, et plus généralement inciter les gens à cotiser.
