### ISSUE TITLE
Créer une fiche de présentation numérique sur le site des CDLT

### ISSUE THREAD

**Issue by ValentineMathieu** [chemins-de-la-transition/Vie-de-l-asso#80]
Point validé lors de la réunion vie asso.
Peu prioritaire, dépend des disponibilités de @J9rem.
Réunion entre Jérémy et moi à organiser pour prévoir plus précisément tout cela.
Faire en sorte que la fiche numérique se retrouve au même endroit que les fiches sur le drive, pour éviter toutes complications.

**Comment by J9rem** [comment]
Juste pour être sûr, ce formulaire ne remplacera pas le formulaire actuel du site vitrine : https://lescheminsdelatransition.org/contact/
Il est juste présent pour faciliter la création d'une fiche contributeur.

**Comment by J9rem** [comment]
Est-ce que quelque chose comme ça irait ?
https://lescheminsdelatransition.org/plateforme/?AjouterUneFiche_Contributeur
Il manque le côté création au format pdf

**Comment by ValentineMathieu** [comment]
@J9rem Yes moi je trouve ca super ! Peut être séparer la partie "fiche contact" de la partie questions, pour un peu plus de clarté (par exemple insérer un titre pour chaque partie, ou espacer les deux parties) mais c'est un détail ! Trop top :) 
Et le formulaire contact va être modifié et écourté après discussions avec Mathieu et Laure, je séparerai le menu contact et pré inscriptions en 2, un premier "sous menu" qui serait dédié au premier contact et qui serait donc composé du formulaire déjà existant dans sa nouvelle version (entre autres), et un 2ème sous menu vers lequel les personnes qui auraient reçu un premier retour des CDLT, et qui auraient des compétences intéressantes à mettre à disposition des projets, accèderaient à cette fiche de présentation et aux tutoriels github element et google drive. Si tu souhaites plus d'informations à ce sujet tu peux aller jeter un coup d'oeil à mon support de réunion onboarding qui a été modifié selon les intentions de Laure et Mathieu https://docs.google.com/document/d/1Y7ca7aWSR2BXe1NnjHc52Q7shS8Rz0de885kv8G534E/edit

**Comment by J9rem** [comment]
J'ai fait un choix de mise en forme.
Qu'en penses-tu ?
Je ne vais pas m'attarder sur la génération en pdf pour le moment
