### ISSUE TITLE
Organiser une AG à l'automne 2020

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/Vie-de-l-asso#89]
Organiser une AG à l'automne 2020
_Evoqué le 30/09 en réunion Vie ASso ([cf. CR](https://docs.google.com/document/d/1zaK96H_WmfPdxUX_ZYzRh5ZUIPwnaY822Gw36UgAhh8/edit#))_

- [ ] organiser l'AG pour les CdlT + mutualiser avec les **AG de chaque structure CdlT régionale**
- [ ] sprint clarification du rôle du CA à faire en amont en se basant sur #67 [+ doc associé](https://docs.google.com/document/d/1bw2Ms8SPsBeiTI0qhlFbx4cpz7-ec3n4uag8w02Qzg0/edit)
- [ ] convoquer les adhérents à l'AG
- [ ] annoncer avec une lettre d'information
- [ ] anticiper la restitution (vidéo, lettre d'information)

@GuillaumeAV a été retenu comme pilote de cette organisation en tant que référent du cercle vie asso et président actuel de l'associaiton. Toute aide est bienvenue.

**Comment by Mathieu-CdlT** [comment]
Ajouter des créneaux horaires le soir pour faciliter la disponibilité des membres du CA. 
En profiter pour demander aux participants qui ne l'ont pas fait de régler leur cotisation (en lien avec Valentine). Votants = celleux qui ont cotisé.

**Comment by GuillaumeAV** [comment]
L'AGE des CdlT aura lieu **jeudi 12 novembre à 18h30** sur zoom à minima !

Lien zoom : https://zoom.us/j/93792005114?pwd=bkZIdklHVWtOczdOZjJ4NW5CcjJqZz09
Code d'accès : 123456
