### ISSUE TITLE
Faire le déroulé de l'AG ! 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/Vie-de-l-asso#98]
[A partir de l'ODJ mentionné ici](https://docs.google.com/document/d/1zaK96H_WmfPdxUX_ZYzRh5ZUIPwnaY822Gw36UgAhh8/edit?usp=sharing), sur le [doc de préparation de l'AG](https://docs.google.com/document/d/1mgGZxjyUNZmjPdzblfeyFhN11tsGlepse4TDLmKmae8/edit?usp=sharing)

**Comment by GuillaumeAV** [comment]
[Vous le trouverez ici](https://docs.google.com/document/d/1mgGZxjyUNZmjPdzblfeyFhN11tsGlepse4TDLmKmae8/edit?usp=sharing)

Qu'en pensez vous ?

**Comment by GuillaumeAV** [comment]
Ci-dessous, une proposition pour les interventions : 

Facilitation : @bouviermullerp ? 

8h30 - 18h45 : Accueil des participants, tour de présentation, par @bouviermullerp ?
18h45 - 19h00 : Tour des actualités + discussion, par @Mathieu-CdlT ?
19h00 - 19h15 : Tour des différents chantiers internes + discussion, par @laurecoplo ? 
19h15 - 19h45 : Présentation de la plateforme CdlT + discussion (en option), par Mathieu
19h45 - 20h00 : Présentation des prochains chantiers, par @MargauxSchulz ?
20h00 - 20h15 : Projet de création d’antennes régionales : discussion + vote, par @GuillaumeAV ?
20h-00 - 20h15 : Discussion libre 

Qu'en dites vous ?

**Comment by bouviermullerp** [comment]
@GuillaumeAV je viens de me faire recruter pour aider les restaurateurs pendant le confinement et livrer des plats à vélo le soir entre 19 et 21h et donc pas dispo pour l'AG (mais c'est pour l'intérêt général).
Mon adresse au cas pour l'antenne : 39, rue de l'Union 64400 Oloron Sainte Marie.

**Comment by GuillaumeAV** [comment]
Done!
